version: "3"
services:
  frontend:
    container_name: tim_jiang_client
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontEnd:/usr/src/app
  backend:
    container_name: tim_jiang_server
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    # depends_on:
    #   - mysql
    volumes:
      - ./backEnd:/usr/src/app
  mysql:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 81221tim
      MYSQL_DATABASE: training
      MYSQL_USER: tim
      MYSQL_PASSWORD: 81221tim
    ports:
      - "3307:3306"